### ISSUE TITLE
Bug in Replay Studio

### ISSUE THREAD

**Issue by dmurfet** [metauni/metauniOS#26]
If you try to record two replays in a row, the second time when you click to record the topbar item disappears
<img width="1440" alt="Screenshot 2023-12-21 at 12 50 56 pm" src="https://github.com/metauni/metauniOS/assets/320329/b8e977df-15d3-4212-9623-b8022ff262c2">
<img width="1440" alt="Screenshot 2023-12-21 at 12 50 58 pm" src="https://github.com/metauni/metauniOS/assets/320329/6c080e31-08d1-40e6-a92f-8b40354daa61">

**Comment by blinkybool** [comment]
Fixed
