### ISSUE TITLE
Mystery Replay bug

### ISSUE THREAD

**Issue by dmurfet** [metauni/metauniOS#50]
<img width="1440" alt="Screenshot 2024-01-04 at 6 07 35 pm" src="https://github.com/metauni/metauniOS/assets/320329/3a563533-8b71-483f-9710-dcc7bfac29ff">
<img width="1440" alt="Screenshot 2024-01-04 at 6 07 40 pm" src="https://github.com/metauni/metauniOS/assets/320329/6d49e958-4a1c-4bb4-b9e9-e6865c44eac5">
<img width="1440" alt="Screenshot 2024-01-04 at 6 07 40 pm" src="https://github.com/metauni/metauniOS/assets/320329/ffc18e29-3753-4d71-a49d-071b629ab5c8">

**Comment by dmurfet** [comment]
Sentry links:

https://metauni.sentry.io/issues/4805529387/events/6118b4f5ef524cee818b35f3b0b8b596/
https://metauni.sentry.io/issues/4778903910/events/597f77778a1d48b18af0fdbada34bcda/

**Comment by blinkybool** [comment]
I believe I fixed all of these in 30825ae3a2d542701d384f8a9b86483ec6bae4de
