### ISSUE TITLE
Getting Board URL or Keycode not functioning

### ISSUE THREAD

**Issue by dmurfet** [metauni/metauniOS#62]
Currently if you load into TRS and use the metauni > Boards > Get URL for Board item you will enter the "Select board" state but be unable to actually click on boards.

**Comment by dmurfet** [comment]
Relevant: ghostBoard business https://github.com/metauni/metauniOS/blob/541339e2fd4a810c4881e11612300e0ee326db0f/plugin/src/App.lua#L170

**Comment by dmurfet** [comment]
Fixed with https://github.com/metauni/metauniOS/commit/82a715ab63b6dd92367620d21bfc9452c1b1a9da

**Comment by blinkybool** [comment]
this commit just deletes an empty line?
